version: 1
build:
  binary: sided
  proto:
    path: proto
    third_party_paths:
      - third_party/proto
      - proto_vendor
accounts:
  - name: alice
    coins:
      - 10000000000000000000000000000000uside
      - 10000000000000000000000000000000uusdc

  - name: bob
    mnemonic: actress letter whip youth flip sort announce chief traffic side destroy seek parade warrior awake scan panther nominee harsh spawn differ enroll glue become
    coins:
      - 10000000000000000000000000000000uside
      - 10000000000000000000000000000000uusdc

# faucet:
#   name: bob
#   coins:
#     - 10uside
#   host: 0.0.0.0:4500
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: uside
    evm:
      params:
        evm_denom: uside
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: uside
    mint:
      params:
        mint_denom: uside
    staking:
      params:
        bond_denom: uside
  chain_id: side_1818-1
  consensus_params:
    block:
      max_gas: "100000000"
validators:
  - name: alice
    bonded: 10000000000000000000000uside
    home: $HOME/.side
client:
  openapi:
    path: "docs/static/openapi.yml"
prefix:
  address: "side"
