version: 1
build:
  binary: sidechaind
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 990000000000000000000000bside
- name: bob
  mnemonic: actress letter whip youth flip sort announce chief traffic side destroy seek parade warrior awake scan panther nominee harsh spawn differ enroll glue become
  coins:
  - 10000000000000000000000bside
- name: david
  mnemonic: model talent wild salmon planet sure hill extra select curve royal super split swing liberty february country sibling label donkey pink butter picnic body
  coins:
    - 1000000000000000000bside
faucet:
  name: bob
  coins:
  - 10bside
  host: 0.0.0.0:4500
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: bside
    evm:
      params:
        evm_denom: bside
    gov:
      deposit_params:
        min_deposit:
        - amount: "10000000"
          denom: bside
    mint:
      params:
        mint_denom: bside
    staking:
      params:
        bond_denom: bside
  chain_id: sidechain_7070-2
  consensus_params:
    block:
      max_gas: "100000000"
validators:
- name: alice
  bonded: 10000000000000000000000bside
  app:
    evm-rpc:
      address: 0.0.0.0:8545
      ws-address: 0.0.0.0:8546
  home: $HOME/.sidechaind
client:
  openapi:
    path: "docs/static/openapi.yml"
