version: 1
build:
  binary: sided
  proto:
    path: proto
    third_party_paths:
      - third_party/proto
      - proto_vendor
accounts:
  - name: alice
    coins:
      - 10000000000000000000000000000000uside
      - 10000000000000000000000000000000uusdc
      - 10000000000000000000000000000000uusdt

  - name: bob
    mnemonic: "furnace wild gravity resist heavy beef bundle deliver design service cycle monkey"
    coins:
      - 10000000000000000000000000000000uside
      - 10000000000000000000000000000000uusdc
      - 10000000000000000000000000000000uusdt
# faucet:
#   name: bob
#   coins:
#     - 10uside
#   host: 0.0.0.0:4500
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: uside
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: uside
      params:
        min_deposit:
          - amount: "10000000"
            denom: uside
        voting_period: "60s"
    mint:
      params:
        mint_denom: uside
    staking:
      params:
        bond_denom: uside
  chain_id: side-devnet-1
  consensus_params:
    block:
      max_gas: "100000000"
  yield_params:
    admin: ""
validators:
  - name: alice
    bonded: 10000000000000000000000uside
    home: $HOME/.side
client:
  openapi:
    path: "docs/static/openapi.yml"
prefix:
  address: "side"
